### PR TITLE
ml users updated coords to west lafayette

### PR DESCRIPTION
**Pull request by raokrutarth**

### CODE REVIEW

**Review by TomFanella4 — APPROVED** [review]

**Comment by mpace965** [comment]
Wait I am going to piggyback off of this

**Comment by mpace965** [comment]
This doesn't work

**Comment by mpace965** [comment]
lat and long are strings, it needs a code change. I'll include it

**Comment by mpace965** [comment]
nvm it was my script's problem. Please ignore

**Pull request merged**
